/**
 * @fileType utility
 * @domain inspector
 * @pattern architect-report-formatter
 * @ai-summary Formats the system architect report into markdown for GitHub issues
 */

import type { ArchitectReport } from './index'

/**
 * Format the architectural health report as markdown for posting to GitHub issues.
 */
export function formatArchitectReport(report: ArchitectReport): string {
  const lines: string[] = []

  lines.push(`## Architectural Health Report — Cycle #${report.cycleNumber}`)
  lines.push('')
  lines.push(`_Generated: ${new Date(report.timestamp).toISOString()}_`)
  lines.push('')

  // Summary
  lines.push('### Summary')
  lines.push('')
  lines.push('| Category | Count |')
  lines.push('|----------|-------|')
  lines.push(`| Total Issues | ${report.summary.totalIssues} |`)
  lines.push(`| 🔴 Critical | ${report.summary.critical} |`)
  lines.push(`| 🟡 Warning | ${report.summary.warning} |`)
  lines.push(`| 🔵 Info | ${report.summary.info} |`)
  lines.push('')

  // Top Recommendations
  if (report.recommendations.length > 0) {
    lines.push('### Top Recommendations')
    lines.push('')

    for (const rec of report.recommendations.slice(0, 5)) {
      const icon = rec.priority === 'critical' ? '🔴' : '🟡'
      lines.push(`${icon} **[${rec.dimension}]** ${rec.issue}`)
      lines.push('')
      lines.push(`   - Impact: ${rec.impact}`)
      lines.push(`   - Action: ${rec.action}`)
      lines.push('')
    }
  }

  // Detailed Findings by Dimension
  lines.push('### Detailed Findings')
  lines.push('')

  // Architecture
  const archIssues = report.findings.architecture.issues
  if (archIssues.length > 0) {
    lines.push('#### Architecture')
    lines.push('')
    for (const issue of archIssues.slice(0, 5)) {
      lines.push(`- ${issue.description}`)
    }
    lines.push('')
  }

  // Design System
  const dsIssues = report.findings.designSystem.issues
  if (dsIssues.length > 0) {
    lines.push('#### Design System')
    lines.push('')
    for (const issue of dsIssues.slice(0, 5)) {
      lines.push(`- ${issue.description}`)
    }
    lines.push('')
  }

  // Separation of Concerns
  const socIssues = report.findings.separationOfConcerns.issues
  if (socIssues.length > 0) {
    lines.push('#### Separation of Concerns')
    lines.push('')
    for (const issue of socIssues.slice(0, 5)) {
      lines.push(`- ${issue.description}`)
    }
    lines.push('')
  }

  // Code Quality
  const cqIssues = report.findings.codeQuality.issues
  if (cqIssues.length > 0) {
    lines.push('#### Code Quality')
    lines.push('')
    for (const issue of cqIssues.slice(0, 5)) {
      lines.push(`- ${issue.description}`)
    }
    lines.push('')
  }

  // Systemic Risks
  const srIssues = report.findings.systemicRisks.issues
  if (srIssues.length > 0) {
    lines.push('#### Systemic Risks')
    lines.push('')
    for (const issue of srIssues.slice(0, 5)) {
      lines.push(`- ${issue.description}`)
    }
    lines.push('')
  }

  // Cross-Cutting
  const ccIssues = report.findings.crossCutting.issues
  if (ccIssues.length > 0) {
    lines.push('#### Cross-Cutting Concerns')
    lines.push('')
    for (const issue of ccIssues.slice(0, 5)) {
      lines.push(`- ${issue.description}`)
    }
    lines.push('')
  }

  // Code Reuse
  const crIssues = report.findings.codeReuse.issues
  if (crIssues.length > 0) {
    lines.push('#### Code Reuse / DRY')
    lines.push('')
    for (const issue of crIssues.slice(0, 5)) {
      lines.push(`- ${issue.description}`)
    }
    lines.push('')
  }

  // Footer
  lines.push('---')
  lines.push('_This report is auto-generated by the System Architect inspector plugin._')

  return lines.join('\n')
}
