/**
 * @fileType plugin
 * @domain inspector
 * @pattern security-scanner-plugin
 * @ai-summary Scans for security vulnerabilities in API routes, collections, and source code
 *
 * Runs 4 scans:
 * 1. API routes missing authentication
 * 2. API routes using overrideAccess: true
 * 3. Collections with permissive 'anyone' access on write operations
 * 4. Hardcoded secrets in source files
 *
 * Posts digest to issue and creates GitHub issues for critical findings.
 * Batches findings by rule to avoid creating duplicate issues for the same vulnerability type.
 * No LLM calls — purely deterministic pattern matching.
 */

import type { InspectorPlugin, ActionRequest, InspectorContext } from '../../../core/types'
import type { SecurityFinding } from './rules'
import { runAllScans } from './scanner'

const DEDUP_WINDOW_MINUTES = 23 * 60
const SECURITY_LABEL = 'type:security'
const MAX_ISSUES_PER_CYCLE = 3

/**
 * Group findings by rule so we create one issue per rule (not per file).
 * E.g., 5 routes without auth → 1 issue listing all 5 routes.
 */
function groupFindingsByRule(findings: SecurityFinding[]): Map<string, SecurityFinding[]> {
  const groups = new Map<string, SecurityFinding[]>()
  for (const finding of findings) {
    const existing = groups.get(finding.rule) || []
    existing.push(finding)
    groups.set(finding.rule, existing)
  }
  return groups
}

/**
 * Build the title for a batched issue.
 * Single finding: "[Security] Route without authentication: /api/foo"
 * Multiple: "[Security] 3 routes without authentication"
 */
function buildBatchedTitle(rule: string, findings: SecurityFinding[]): string {
  if (findings.length === 1) {
    return `[Security] ${findings[0].message}`
  }
  // Use the first finding's message as a template, pluralize
  const firstMessage = findings[0].message
  return `[Security] ${findings.length}x: ${firstMessage.split(':')[0]}`
}

/**
 * Build the body for a batched issue listing all affected files.
 */
function buildBatchedBody(rule: string, findings: SecurityFinding[]): string {
  let body = `## Security Vulnerability\n\n`
  body += `**Rule:** \`${rule}\`\n`
  body += `**Findings:** ${findings.length}\n\n`

  body += `### Affected Files\n\n`
  for (const f of findings) {
    body += `- \`${f.file}${f.line ? `:${f.line}` : ''}\` — ${f.message}\n`
  }

  body += `\n### Details\n\n`
  // Show detail for first finding as representative
  body += '```\n' + findings[0].detail + '\n```\n\n'

  if (findings.length > 1) {
    body += `_${findings.length - 1} additional files have the same issue._\n\n`
  }

  body += `_Auto-generated by the Security Scanner inspector plugin on ${new Date().toISOString()}_`

  return body
}

/**
 * Build a GitHub search query to find existing open issues for this rule.
 * Uses quoted title text + label filter.
 */
function buildSearchQuery(rule: string): string {
  // Search for any open security issue mentioning this rule
  return `"[Security]" label:${SECURITY_LABEL} is:open "${rule}"`
}

/**
 * Security Scanner plugin.
 *
 * Runs ~daily (every 6th cycle + 23h dedup).
 */
export const securityScannerPlugin: InspectorPlugin = {
  name: 'security-scanner',
  description: 'Scan for security vulnerabilities in API routes, collections, and source code',
  domain: 'project',
  schedule: { every: 1 }, // Daily

  async run(ctx): Promise<ActionRequest[]> {
    ctx.log.debug('Running security-scanner plugin')

    const findings = runAllScans(process.cwd())

    if (findings.length === 0) {
      ctx.log.info('No security findings — skipping security-scanner')
      return []
    }

    ctx.log.info(
      {
        totalFindings: findings.length,
        critical: findings.filter((f) => f.severity === 'critical').length,
        high: findings.filter((f) => f.severity === 'high').length,
        medium: findings.filter((f) => f.severity === 'medium').length,
      },
      'Security scan complete',
    )

    const actions: ActionRequest[] = []

    // Digest comment action
    if (ctx.digestIssue) {
      actions.push({
        plugin: 'security-scanner',
        type: 'digest',
        urgency: 'info',
        title: '🔒 Security Scan Report',
        detail: formatDigestSummary(findings),
        dedupKey: 'security-scanner:digest-daily',
        dedupWindowMinutes: DEDUP_WINDOW_MINUTES,
        async execute(execCtx: InspectorContext): Promise<{ success: boolean; message?: string }> {
          if (!execCtx.digestIssue) {
            return { success: false, message: 'Digest issue not configured at execution time' }
          }
          const markdown = formatDigestMarkdown(findings, execCtx.cycleNumber)
          execCtx.github.postComment(execCtx.digestIssue, markdown)
          return { success: true, message: 'Digest posted' }
        },
      })
    }

    // Group critical findings by rule and create one issue per rule (not per file)
    const criticalFindings = findings.filter((f) => f.severity === 'critical')
    const grouped = groupFindingsByRule(criticalFindings)

    let issueCount = 0
    for (const [rule, ruleFindings] of grouped) {
      if (issueCount >= MAX_ISSUES_PER_CYCLE) break

      const dedupKey = `security-scanner:issue:${rule}`
      const title = buildBatchedTitle(rule, ruleFindings)

      actions.push({
        plugin: 'security-scanner',
        type: 'create-issue',
        urgency: 'critical',
        title,
        detail: `${ruleFindings.length} finding(s) for rule ${rule}`,
        dedupKey,
        dedupWindowMinutes: DEDUP_WINDOW_MINUTES,
        async execute(execCtx: InspectorContext): Promise<{ success: boolean; message?: string }> {
          // Check for existing open issue for this rule to avoid duplicates
          const searchQuery = buildSearchQuery(rule)
          const existing = execCtx.github.searchIssues(searchQuery)
          if (existing.length > 0) {
            return {
              success: true,
              message: `Issue already exists for rule '${rule}' (#${existing[0].number}) — skipping`,
            }
          }

          const body = buildBatchedBody(rule, ruleFindings)
          const issueNumber = execCtx.github.createIssue(title, body, [SECURITY_LABEL])
          if (issueNumber) {
            return {
              success: true,
              message: `Created batched issue #${issueNumber} for ${ruleFindings.length} finding(s)`,
            }
          }
          return { success: false, message: 'Failed to create issue' }
        },
      })
      issueCount++
    }

    return actions
  },
}

// ============================================================================
// Formatting helpers
// ============================================================================

function formatDigestSummary(
  findings: Array<{ severity: string; file: string; message: string }>,
): string {
  const critical = findings.filter((f) => f.severity === 'critical').length
  const high = findings.filter((f) => f.severity === 'high').length
  const medium = findings.filter((f) => f.severity === 'medium').length
  const low = findings.filter((f) => f.severity === 'low').length

  return `Security scan: ${findings.length} findings (${critical} critical, ${high} high, ${medium} medium, ${low} low)`
}

function formatDigestMarkdown(
  findings: Array<{
    severity: string
    file: string
    message: string
    detail: string
    line?: number
  }>,
  cycleNumber: number,
): string {
  const severityCounts = {
    critical: findings.filter((f) => f.severity === 'critical').length,
    high: findings.filter((f) => f.severity === 'high').length,
    medium: findings.filter((f) => f.severity === 'medium').length,
    low: findings.filter((f) => f.severity === 'low').length,
  }

  let markdown = `## 🔒 Security Scan Report — Cycle #${cycleNumber}\n\n`
  markdown += `| Severity | Count |\n|----------|-------|\n`
  markdown += `| 🔴 Critical | ${severityCounts.critical} |\n`
  markdown += `| 🟠 High | ${severityCounts.high} |\n`
  markdown += `| 🟡 Medium | ${severityCounts.medium} |\n`
  markdown += `| 🟢 Low | ${severityCounts.low} |\n\n`

  if (findings.length > 0) {
    markdown += `### Findings\n\n`
    markdown += `| Severity | File | Message |\n|----------|------|---------|\n`
    for (const f of findings.slice(0, 20)) {
      const severityIcon =
        f.severity === 'critical'
          ? '🔴'
          : f.severity === 'high'
            ? '🟠'
            : f.severity === 'medium'
              ? '🟡'
              : '🟢'
      markdown += `| ${severityIcon} ${f.severity} | \`${f.file}${f.line ? `:${f.line}` : ''}\` | ${f.message} |\n`
    }
    if (findings.length > 20) {
      markdown += `\n_... and ${findings.length - 20} more findings_\n`
    }
  }

  markdown += `\n_Generated by Security Scanner on ${new Date().toISOString()}_`

  return markdown
}
