/**
 * @fileType utility
 * @domain inspector
 * @pattern api-surface-formatter
 * @ai-summary Formats API surface catalog into markdown for digest comments
 */

import type { ApiCatalog } from './cataloger'

/**
 * Format the API surface catalog as a markdown digest for the digest issue.
 */
export function formatApiSurfaceDigest(catalog: ApiCatalog, cycleNumber: number): string {
  let markdown = `## 🌐 API Surface Audit — Cycle #${cycleNumber}\n\n`

  // Summary stats
  markdown += `### Summary\n\n`
  markdown += `| Metric | Count | Percentage |\n`
  markdown += `|--------|-------|------------|\n`
  markdown += `| Total Routes | ${catalog.totalRoutes} | — |\n`
  markdown += `| Authenticated | ${catalog.authenticatedRoutes} | ${Math.round((catalog.authenticatedRoutes / catalog.totalRoutes) * 100)}% |\n`
  markdown += `| Unauthenticated | ${catalog.unauthenticatedRoutes} | ${Math.round((catalog.unauthenticatedRoutes / catalog.totalRoutes) * 100)}% |\n`
  markdown += `| With Validation | ${catalog.withValidation} | ${Math.round((catalog.withValidation / catalog.totalRoutes) * 100)}% |\n`
  markdown += `| With Error Handling | ${catalog.withErrorHandling} | ${Math.round((catalog.withErrorHandling / catalog.totalRoutes) * 100)}% |\n\n`

  // Flags section
  if (catalog.flags.length > 0) {
    markdown += `### Flags (${catalog.flags.length})\n\n`
    markdown += `| Severity | Route | Issue |\n|----------|-------|-------|\n`
    for (const flag of catalog.flags.slice(0, 15)) {
      const severityIcon =
        flag.severity === 'high' ? '🟠' : flag.severity === 'medium' ? '🟡' : '🟢'
      markdown += `| ${severityIcon} ${flag.severity} | \`${flag.route}\` | ${flag.issue} |\n`
    }
    if (catalog.flags.length > 15) {
      markdown += `\n_... and ${catalog.flags.length - 15} more flags_\n`
    }
    markdown += '\n'
  }

  // Full route table (truncated for readability)
  markdown += `### Routes (${catalog.totalRoutes})\n\n`
  markdown += `| API Path | Methods | Auth | Validation | Errors |\n|----------|---------|------|------------|--------|\n`

  // Show first 30 routes
  const displayRoutes = catalog.routes.slice(0, 30)
  for (const route of displayRoutes) {
    const methods = route.methods.join(', ') || '—'
    const auth = route.authPattern === 'none' ? '❌' : '✅'
    const validation = route.hasZodValidation ? '✅' : '❌'
    const errors = route.hasErrorHandling ? '✅' : '❌'
    markdown += `| ${route.apiPath} | ${methods} | ${auth} | ${validation} | ${errors} |\n`
  }

  if (catalog.routes.length > 30) {
    markdown += `\n_... and ${catalog.routes.length - 30} more routes_\n`
  }

  markdown += `\n_Generated by API Surface Auditor on ${new Date().toISOString()}_`

  return markdown
}

/**
 * Format a compact Slack-friendly version of the catalog.
 */
export function formatApiSurfaceSlack(catalog: ApiCatalog): string {
  const highFlags = catalog.flags.filter((f) => f.severity === 'high').length
  const mediumFlags = catalog.flags.filter((f) => f.severity === 'medium').length

  let text = `🌐 API Surface: ${catalog.totalRoutes} routes`
  text += ` | ${catalog.authenticatedRoutes} auth`
  text += ` | ${catalog.withValidation} validated`

  if (highFlags > 0 || mediumFlags > 0) {
    text += ` | ⚠️ ${highFlags} high, ${mediumFlags} medium flags`
  }

  return text
}

/**
 * Format only the critical flags as a separate warning digest.
 */
export function formatCriticalFlags(catalog: ApiCatalog): string {
  const criticalFlags = catalog.flags.filter((f) => f.severity === 'high')

  if (criticalFlags.length === 0) return ''

  let markdown = `## ⚠️ API Surface Critical Flags\n\n`
  markdown += `| Route | Issue |\n|-------|-------|\n`

  for (const flag of criticalFlags) {
    markdown += `| \`${flag.route}\` | ${flag.issue} |\n`
  }

  return markdown
}
