/**
 * @fileType utility
 * @domain inspector
 * @pattern failure-miner-reporter
 * @ai-summary Formats failure pattern analysis into GitHub issue bodies
 */

import type { MinerAnalysis } from './analyzer'

/** Strip GitHub search qualifiers to prevent injection */
function sanitizeSearchTerm(term: string): string {
  return term.replace(/[:]/g, ' ').trim().slice(0, 100)
}

/**
 * Format an issue title for a stage-hotspot finding.
 */
export function formatHotspotTitle(stage: string, count: number): string {
  return `[Cody] Stage hotspot: '${stage}' failing repeatedly (${count}x)`
}

/**
 * Format an issue title for an error-pattern finding.
 */
export function formatErrorPatternTitle(label: string, count: number): string {
  return `[Cody] Recurring error pattern: ${label} (${count}x)`
}

/**
 * Format the body of a stage-hotspot GitHub issue.
 */
export function formatHotspotBody(analysis: MinerAnalysis, stage: string, count: number): string {
  const percent = Math.round((count / analysis.totalFailures) * 100)
  return `## Cody Pipeline — Stage Hotspot Detected

The \`${stage}\` stage has failed **${count} times** (${percent}% of all ${analysis.totalFailures} failures detected in the last scan).

### What this means

This stage may have a systemic issue that is causing repeated pipeline failures. Investigate the \`${stage}\` stage logic, prompts, or dependencies.

### Next Steps

1. Review recent \`${stage}\` stage logs across failed tasks
2. Check for common error patterns in those failures
3. Consider improving the stage's error handling or retry logic

_Auto-generated by the Failure Pattern Miner inspector plugin on ${analysis.analysisDate}_`
}

/**
 * Format the body of an error-pattern GitHub issue.
 */
export function formatErrorPatternBody(
  analysis: MinerAnalysis,
  label: string,
  count: number,
  affectedTaskIds: string[],
): string {
  const taskList = affectedTaskIds
    .slice(0, 10)
    .map((id) => `- \`${id}\``)
    .join('\n')
  const moreCount = affectedTaskIds.length > 10 ? ` (+${affectedTaskIds.length - 10} more)` : ''

  return `## Cody Pipeline — Recurring Error Pattern

The error pattern \`${label}\` has appeared **${count} times** across ${affectedTaskIds.length} tasks in the last scan.

### Affected Tasks (sample)

${taskList}${moreCount}

### What this means

This error pattern is occurring repeatedly and may indicate a systemic issue with pipeline configuration, environment, or agent prompts.

### Next Steps

1. Investigate the root cause of \`${label}\` errors
2. Review task logs for the affected tasks above
3. Consider adding a targeted fix or guard in the relevant stage

_Auto-generated by the Failure Pattern Miner inspector plugin on ${analysis.analysisDate}_`
}

/**
 * Build a dedup search query for a hotspot issue.
 */
export function hotspotSearchQuery(stage: string): string {
  const safe = sanitizeSearchTerm(stage)
  return `[Cody] Stage hotspot: '${safe}' in:title is:open label:cody:improvement`
}

/**
 * Build a dedup search query for an error-pattern issue.
 */
export function errorPatternSearchQuery(label: string): string {
  const safe = sanitizeSearchTerm(label)
  return `[Cody] Recurring error pattern: ${safe} in:title is:open label:cody:improvement`
}
