/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
    'payload-mcp-api-keys': PayloadMcpApiKeyAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    categories: Category;
    config_secrets: ConfigSecret;
    config_values: ConfigValue;
    config_audit_logs: ConfigAuditLog;
    conversations: Conversation;
    'guest-sessions': GuestSession;
    memory_items: MemoryItem;
    tenants: Tenant;
    courses: Course;
    chapters: Chapter;
    lessons: Lesson;
    exercises: Exercise;
    prompts: Prompt;
    'exercise-assets': ExerciseAsset;
    users: User;
    'user-progress': UserProgress;
    media: Media;
    posts: Post;
    'pricing-plans': PricingPlan;
    'mcp-audit-logs': McpAuditLog;
    redirects: Redirect;
    forms: Form;
    'form-submissions': FormSubmission;
    search: Search;
    'payload-mcp-api-keys': PayloadMcpApiKey;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-folders': FolderInterface;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    'payload-folders': {
      documentsAndFolders: 'payload-folders' | 'media';
    };
  };
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    config_secrets: ConfigSecretsSelect<false> | ConfigSecretsSelect<true>;
    config_values: ConfigValuesSelect<false> | ConfigValuesSelect<true>;
    config_audit_logs: ConfigAuditLogsSelect<false> | ConfigAuditLogsSelect<true>;
    conversations: ConversationsSelect<false> | ConversationsSelect<true>;
    'guest-sessions': GuestSessionsSelect<false> | GuestSessionsSelect<true>;
    memory_items: MemoryItemsSelect<false> | MemoryItemsSelect<true>;
    tenants: TenantsSelect<false> | TenantsSelect<true>;
    courses: CoursesSelect<false> | CoursesSelect<true>;
    chapters: ChaptersSelect<false> | ChaptersSelect<true>;
    lessons: LessonsSelect<false> | LessonsSelect<true>;
    exercises: ExercisesSelect<false> | ExercisesSelect<true>;
    prompts: PromptsSelect<false> | PromptsSelect<true>;
    'exercise-assets': ExerciseAssetsSelect<false> | ExerciseAssetsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'user-progress': UserProgressSelect<false> | UserProgressSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    'pricing-plans': PricingPlansSelect<false> | PricingPlansSelect<true>;
    'mcp-audit-logs': McpAuditLogsSelect<false> | McpAuditLogsSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    search: SearchSelect<false> | SearchSelect<true>;
    'payload-mcp-api-keys': PayloadMcpApiKeysSelect<false> | PayloadMcpApiKeysSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-folders': PayloadFoldersSelect<false> | PayloadFoldersSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    header: Header;
    footer: Footer;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
  };
  locale: null;
  user:
    | (User & {
        collection: 'users';
      })
    | (PayloadMcpApiKey & {
        collection: 'payload-mcp-api-keys';
      });
  jobs: {
    tasks: {
      pdf_to_exercises: TaskPdfToExercises;
      pdf_to_exercises_v2: TaskPdfToExercisesV2;
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface PayloadMcpApiKeyAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  title: string;
  hero: {
    type: 'none' | 'highImpact' | 'mediumImpact' | 'lowImpact';
    richText?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    links?:
      | {
          link: {
            type?: ('reference' | 'custom') | null;
            newTab?: boolean | null;
            reference?: {
              relationTo: 'pages';
              value: string | Page;
            } | null;
            url?: string | null;
            label: string;
            /**
             * Choose how the link should be rendered.
             */
            appearance?: ('default' | 'outline') | null;
          };
          id?: string | null;
        }[]
      | null;
  };
  layout: (CallToActionBlock | ContentBlock | ArchiveBlock | FormBlock | HtmlBlock)[];
  meta?: {
    title?: string | null;
    description?: string | null;
  };
  publishedAt?: string | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  /**
   * User who created this document
   */
  createdBy?: (string | null) | User;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock".
 */
export interface CallToActionBlock {
  richText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  links?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?: {
            relationTo: 'pages';
            value: string | Page;
          } | null;
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock".
 */
export interface ContentBlock {
  columns?:
    | {
        size?: ('oneThird' | 'half' | 'twoThirds' | 'full') | null;
        richText?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        enableLink?: boolean | null;
        link?: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?: {
            relationTo: 'pages';
            value: string | Page;
          } | null;
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'content';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock".
 */
export interface ArchiveBlock {
  introContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  populateBy?: ('collection' | 'selection') | null;
  relationTo?: 'courses' | null;
  categories?: (string | Category)[] | null;
  limit?: number | null;
  selectedDocs?:
    | {
        relationTo: 'courses';
        value: string | Course;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'archive';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: string;
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  /**
   * User who created this document
   */
  createdBy?: (string | null) | User;
  parent?: (string | null) | Category;
  breadcrumbs?:
    | {
        doc?: (string | null) | Category;
        url?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name?: string | null;
  role: 'admin' | 'student';
  googleSub?: string | null;
  verifiedEmail?: string | null;
  registrationMethod?: ('google' | 'email') | null;
  registeredAt?: string | null;
  googleProfile?: {
    name?: string | null;
  };
  oauthLoginSecretEnc?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses".
 */
export interface Course {
  id: string;
  /**
   * Tenant scope for this document
   */
  tenant: string | Tenant;
  /**
   * Course identifier (e.g., "ח" or "8")
   */
  courseLabel: string;
  /**
   * Display title (e.g., "Course 8 Math")
   */
  title: string;
  /**
   * Detailed description of the course
   */
  description?: string | null;
  /**
   * Upload course-related media files (images, videos, documents, etc.)
   */
  mediaFiles?: (string | Media)[] | null;
  /**
   * Sort order for UI display
   */
  order: number;
  /**
   * Publication status of the course
   */
  status: 'draft' | 'published' | 'archived';
  /**
   * Whether this course is currently active
   */
  isActive: boolean;
  categories: (string | Category)[];
  /**
   * AI system prompt for Ask tab chat in this course (uses default if not set)
   */
  prompt?: (string | null) | Prompt;
  /**
   * AI context text for this course. Injected into Ask tab chat prompts at runtime.
   */
  courseContextText?: string | null;
  /**
   * URL-friendly identifier (auto-generated from title if empty)
   */
  slug?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
  };
  /**
   * User who created this document
   */
  createdBy?: (string | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants".
 */
export interface Tenant {
  id: string;
  /**
   * Tenant display name
   */
  name: string;
  /**
   * Tenant slug (used to resolve default tenant from env)
   */
  slug: string;
  /**
   * Tenant status flag
   */
  status?: ('active' | 'archived') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  /**
   * Tenant scope for this document
   */
  tenant: string | Tenant;
  /**
   * Auto-detected from file type (admin can override)
   */
  type: 'image' | 'video' | 'audio' | 'pdf' | 'svg' | 'document' | 'external' | 'other';
  /**
   * URL for external embed or link
   */
  externalUrl?: string | null;
  /**
   * Alternative text for images and SVGs (required for accessibility)
   */
  alt?: string | null;
  caption?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * User who created this document
   */
  createdBy?: (string | null) | User;
  retentionPolicy: 'persistent' | 'ephemeral';
  /**
   * Auto-set for ephemeral media (30 days from creation)
   */
  expiresAt?: string | null;
  /**
   * Responsive image sizes metadata (auto-generated by blob storage)
   */
  sizes?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  folder?: (string | null) | FolderInterface;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders".
 */
export interface FolderInterface {
  id: string;
  name: string;
  folder?: (string | null) | FolderInterface;
  documentsAndFolders?: {
    docs?: (
      | {
          relationTo?: 'payload-folders';
          value: string | FolderInterface;
        }
      | {
          relationTo?: 'media';
          value: string | Media;
        }
    )[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  folderType?: 'media'[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "prompts".
 */
export interface Prompt {
  id: string;
  /**
   * Human-readable prompt name
   */
  title: string;
  /**
   * Machine-readable key (e.g., "default-tutor-v1")
   */
  key?: string | null;
  /**
   * System prompts are always included. Context prompts are lesson-specific.
   */
  type: 'system' | 'context';
  /**
   * System prompt template for AI tutor
   */
  template: string;
  /**
   * Only "published" prompts are used at runtime
   */
  status: 'draft' | 'published' | 'archived';
  /**
   * Use as fallback when lesson has no prompt
   */
  isDefaultForAgentChat?: boolean | null;
  /**
   * Tenant scope for this document
   */
  tenant: string | Tenant;
  /**
   * Purpose of this prompt: chat conversation, PDF extraction, or PDF verification
   */
  usage?: ('chat' | 'extractor' | 'verifier') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock".
 */
export interface FormBlock {
  form: string | Form;
  enableIntro?: boolean | null;
  introContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'formBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: string;
  title: string;
  fields?:
    | (
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkbox';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'country';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'email';
          }
        | {
            message?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'message';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'number';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            placeholder?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'select';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'state';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textarea';
          }
      )[]
    | null;
  submitButtonLabel?: string | null;
  /**
   * Choose whether to display an on-page message or redirect to a different page after they submit the form.
   */
  confirmationType?: ('message' | 'redirect') | null;
  confirmationMessage?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  redirect?: {
    url: string;
  };
  /**
   * Send custom emails when the form submits. Use comma separated lists to send the same email to multiple recipients. To reference a value from this form, wrap that field's name with double curly brackets, i.e. {{firstName}}. You can use a wildcard {{*}} to output all data and {{*:table}} to format it as an HTML table in the email.
   */
  emails?:
    | {
        emailTo?: string | null;
        cc?: string | null;
        bcc?: string | null;
        replyTo?: string | null;
        emailFrom?: string | null;
        subject: string;
        /**
         * Enter the message that should be sent in this email.
         */
        message?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HtmlBlock".
 */
export interface HtmlBlock {
  /**
   * Enter HTML content. Links must be relative (/path or #anchor). Allowed attributes: class, id, data-* on all tags; href (required), title, class, id, data-* on <a> tags; plus safe SVG attributes (e.g., viewBox, fill, stroke, d). No style=, target=, or on*= attributes allowed. The <style> tag is allowed.
   */
  html: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'html';
}
/**
 * Tenant-scoped encrypted secrets. All values are always encrypted.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "config_secrets".
 */
export interface ConfigSecret {
  id: string;
  /**
   * Configuration key (snake_case, immutable after creation)
   */
  key: string;
  /**
   * Tenant this secret belongs to
   */
  tenant: string | Tenant;
  /**
   * Optional title/description for this secret
   */
  title?: string | null;
  /**
   * Secret value (write-only after save)
   */
  value: string;
  /**
   * Enable or disable this secret
   */
  enabled: boolean;
  updatedAt: string;
  createdAt: string;
}
/**
 * Tenant-scoped configuration values stored as JSON. Organized by feature domain (chat, pdf_conversion, global).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "config_values".
 */
export interface ConfigValue {
  id: string;
  /**
   * Feature domain for this configuration
   */
  domain: 'chat' | 'pdf_conversion' | 'global' | 'guest_chat';
  /**
   * Tenant this configuration belongs to
   */
  tenant: string | Tenant;
  /**
   * Configuration values as JSON object
   */
  config:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Optional description of this configuration
   */
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Append-only audit log for config secret mutations. Secrets never stored in plaintext.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "config_audit_logs".
 */
export interface ConfigAuditLog {
  id: string;
  /**
   * Configuration key that was modified
   */
  key: string;
  /**
   * Tenant of the mutated config entry
   */
  tenant: string | Tenant;
  /**
   * Action performed
   */
  action: 'created' | 'updated' | 'enabled' | 'disabled';
  /**
   * Admin user who performed the action
   */
  actor: string | User;
  /**
   * Optional reason for the change
   */
  reason?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Context-scoped chat conversations with AI tutor
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "conversations".
 */
export interface Conversation {
  id: string;
  /**
   * Student who owns this conversation (null for guest-owned)
   */
  user?: (string | null) | User;
  /**
   * Guest session owner (set for anonymous chats)
   */
  guestSession?: (string | null) | GuestSession;
  /**
   * Polymorphic context reference (Course/Chapter/Lesson/Exercise/Tenant)
   */
  contextRef:
    | {
        relationTo: 'courses';
        value: string | Course;
      }
    | {
        relationTo: 'chapters';
        value: string | Chapter;
      }
    | {
        relationTo: 'lessons';
        value: string | Lesson;
      }
    | {
        relationTo: 'exercises';
        value: string | Exercise;
      }
    | {
        relationTo: 'tenants';
        value: string | Tenant;
      };
  /**
   * Derived key for indexing (e.g., "exercises:abc123")
   */
  contextKey?: string | null;
  /**
   * Legacy field - use contextRef instead. Will be removed in future version.
   */
  exercise?: (string | null) | Exercise;
  /**
   * Conversation message history
   */
  messages?:
    | {
        role: 'user' | 'assistant';
        /**
         * Message content
         */
        content: string;
        timestamp: string;
        /**
         * Hidden messages are persisted for LLM context but excluded from client responses
         */
        hidden?: boolean | null;
        /**
         * Media attachments for this message (max 5)
         */
        media?:
          | {
              mediaId: string | Media;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Compressed history of older messages
   */
  summary?: string | null;
  /**
   * When summary was last updated
   */
  summaryUpdatedAt?: string | null;
  /**
   * Summary includes messages up to this timestamp
   */
  summaryUntilTimestamp?: string | null;
  /**
   * Version of prompt composition policy
   */
  contextPolicyVersion: string;
  /**
   * Timestamp of last message (auto-updated)
   */
  lastMessageAt: string;
  /**
   * When this conversation was archived. Missing = active.
   */
  archivedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Anonymous user sessions for guest chat
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "guest-sessions".
 */
export interface GuestSession {
  id: string;
  /**
   * SHA-256 hash of session token (never store raw token)
   */
  tokenHash: string;
  /**
   * Allows token rotation/invalidation without session deletion
   */
  tokenVersion: number;
  /**
   * Session creation timestamp
   */
  createdAt: string;
  /**
   * Last activity timestamp (extends sliding TTL)
   */
  lastActiveAt: string;
  /**
   * Sliding TTL expiration (extends on activity, clamped by hard cap)
   */
  expiresAt: string;
  /**
   * Absolute hard cap - session cannot extend beyond this
   */
  hardExpiresAt: string;
  /**
   * SHA-256 hash of IP address (privacy-preserving abuse tracking)
   */
  ipHash?: string | null;
  /**
   * SHA-256 hash of User-Agent (privacy-preserving abuse tracking)
   */
  userAgentHash?: string | null;
  /**
   * Session status: active = usable, expired = past TTL, revoked = claimed by user
   */
  status: 'active' | 'expired' | 'revoked';
  /**
   * User who claimed this session on upgrade
   */
  claimedByUser?: (string | null) | User;
  /**
   * When this session was claimed by a user
   */
  claimedAt?: string | null;
  /**
   * Total messages sent in this guest session (capped at GUEST_SESSION_MAX_MESSAGES)
   */
  messageCount: number;
  updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "chapters".
 */
export interface Chapter {
  id: string;
  /**
   * Tenant scope for this document
   */
  tenant: string | Tenant;
  /**
   * The course this chapter belongs to
   */
  course: string | Course;
  /**
   * Chapter identifier (e.g., "1", "A", "א")
   */
  chapterLabel?: string | null;
  /**
   * Chapter title
   */
  title: string;
  /**
   * Auto-computed display title for admin (chapter title — course title)
   */
  adminTitle?: string | null;
  /**
   * Detailed description of the chapter
   */
  description?: string | null;
  /**
   * Upload chapter-related media files (images, videos, documents, etc.)
   */
  mediaFiles?: (string | Media)[] | null;
  /**
   * Sort order within the course
   */
  order: number;
  /**
   * Publication status of the chapter
   */
  status: 'draft' | 'published' | 'archived';
  /**
   * Whether this chapter is currently active
   */
  isActive: boolean;
  /**
   * URL-friendly identifier (auto-generated from title if empty)
   */
  slug?: string | null;
  /**
   * User who created this document
   */
  createdBy?: (string | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lessons".
 */
export interface Lesson {
  id: string;
  /**
   * Tenant scope for this document
   */
  tenant: string | Tenant;
  /**
   * The chapter this lesson belongs to
   */
  chapter: string | Chapter;
  /**
   * The type of lesson: Learning content, Practice exercises, or Exam
   */
  type: 'learning' | 'practice' | 'exam';
  /**
   * Lesson title
   */
  title: string;
  /**
   * Detailed description of the lesson
   */
  description?: string | null;
  /**
   * Sort order within the course
   */
  order: number;
  /**
   * Publication status of the lesson
   */
  status: 'draft' | 'published' | 'archived';
  /**
   * Whether this lesson is currently active
   */
  isActive: boolean;
  /**
   * Show an intro/about page before the lesson starts
   */
  introEnabled?: boolean | null;
  /**
   * HTML content for the intro page. Supports raw HTML (bold, lists, etc).
   */
  introDescription?: string | null;
  /**
   * Image, SVG, or video displayed on the intro page
   */
  introMedia?: (string | null) | Media;
  /**
   * Upload lesson content files (PDFs, videos, images, etc.)
   */
  contentFiles?: (string | Media)[] | null;
  /**
   * AI context text for this lesson. Injected into chat prompts at runtime. NOT indexed or searchable.
   */
  lessonContextText?: string | null;
  /**
   * AI system prompt for this lesson (uses default if not set)
   */
  prompt?: (string | null) | Prompt;
  /**
   * URL-friendly identifier (auto-generated from title if empty)
   */
  slug?: string | null;
  /**
   * User who created this document
   */
  createdBy?: (string | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "exercises".
 */
export interface Exercise {
  id: string;
  /**
   * Tenant scope for this document
   */
  tenant: string | Tenant;
  /**
   * Exercise title (for admin reference)
   */
  title: string;
  /**
   * Order of exercise within the lesson (lower numbers appear first)
   */
  order: number;
  /**
   * The lesson this exercise belongs to
   */
  lesson: string | Lesson;
  /**
   * URL-friendly identifier (auto-generated from title, unique within lesson)
   */
  slug?: string | null;
  /**
   * Ordered blocks stream. Use question_* blocks to add questions, and rich_text blocks for instructions/notes between questions.
   */
  content:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * User who created this document
   */
  createdBy?: (string | null) | User;
  origin: 'manual' | 'conversion' | 'import';
  /**
   * Original PDF media for conversion exercises
   */
  sourceDoc?: (string | null) | Media;
  /**
   * Payload job ID that created this exercise
   */
  conversionJobId?: string | null;
  /**
   * Starting page in source PDF
   */
  sourcePageStart?: number | null;
  /**
   * Ending page in source PDF
   */
  sourcePageEnd?: number | null;
  /**
   * Order within the segment (1-indexed)
   */
  sourceOrderInSegment?: number | null;
  /**
   * SHA256 hash for deduplication
   */
  contentHash?: string | null;
  /**
   * Source-based identity key (tenant:lesson:doc:pages:ordinal:version)
   */
  idempotencyKey?: string | null;
  /**
   * Extraction spec version for idempotency key stability
   */
  specVersion?: string | null;
  /**
   * Additional extraction metadata (segmentIndex, itemOrdinal)
   */
  extractionMeta?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Pipeline version (1=text extraction, 2=image crops)
   */
  pipelineVersion?: number | null;
  /**
   * Zero-based page index in source PDF (V2 image crops)
   */
  sourcePageIndex?: number | null;
  /**
   * Normalized bounding box {x,y,width,height} 0..1 (V2 image crops)
   */
  sourceBboxNormalized?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Long-term memory items for AI chat context
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "memory_items".
 */
export interface MemoryItem {
  id: string;
  /**
   * User ID for filtering (scalar field, NOT a relationship)
   */
  userId: string;
  /**
   * Optional conversation scope (scalar field, NOT a relationship)
   */
  conversationId?: string | null;
  /**
   * Context key (e.g., lessons:abc123) for scoped retrieval
   */
  contextKey?: string | null;
  /**
   * Context level where memory was extracted (analytics/debug only)
   */
  contextLevel?: ('exercise' | 'lesson' | 'chapter' | 'course' | 'global') | null;
  /**
   * Category of memory item
   */
  type: 'preference' | 'decision' | 'fact' | 'open_loop' | 'profile' | 'constraint' | 'other';
  /**
   * The memory content (max 2000 chars)
   */
  text: string;
  /**
   * Vector embedding (1536 dimensions) - auto-generated
   */
  embedding:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Importance scale 1-5 (higher = more important)
   */
  importance: number;
  /**
   * Status (use deprecated instead of deleting)
   */
  status: 'active' | 'deprecated';
  /**
   * Metadata about where this memory came from
   */
  source: {
    /**
     * Conversation where this memory was extracted
     */
    sourceConversationId?: string | null;
    /**
     * Timestamp of source message
     */
    sourceMessageTimestamp: string;
    /**
     * Who said the message this memory came from
     */
    sourceMessageRole: 'user' | 'assistant';
  };
  /**
   * Convenience field for admin UI - DO NOT use for filtering
   */
  user?: (string | null) | User;
  /**
   * Convenience field for admin UI - DO NOT use for filtering
   */
  conversation?: (string | null) | Conversation;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "exercise-assets".
 */
export interface ExerciseAsset {
  id: string;
  /**
   * Alt text for accessibility
   */
  alt: string;
  /**
   * Optional caption for the figure
   */
  caption?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * User who created this document
   */
  createdBy?: (string | null) | User;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-progress".
 */
export interface UserProgress {
  id: string;
  /**
   * Tenant scope for this document
   */
  tenant: string | Tenant;
  /**
   * The user this progress belongs to
   */
  user: string | User;
  /**
   * Grade level (e.g., "8", "ח")
   */
  gradeLevel?: string | null;
  progressRecords?:
    | {
        recordType: 'chapter' | 'lesson' | 'exercise';
        /**
         * ID of the chapter, lesson, or exercise
         */
        recordId: string;
        /**
         * Completion percentage (0-100)
         */
        completionPercentage?: number | null;
        status?: ('not_started' | 'in_progress' | 'completed') | null;
        /**
         * Score for exercises (0-100)
         */
        score?: number | null;
        /**
         * Last time this record was accessed
         */
        lastAccessedAt?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: string;
  title: string;
  heroImage?: (string | null) | Media;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  relatedPosts?: (string | Post)[] | null;
  categories?: (string | Category)[] | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  authors?: (string | User)[] | null;
  populatedAuthors?:
    | {
        id?: string | null;
        name?: string | null;
      }[]
    | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  /**
   * User who created this document
   */
  createdBy?: (string | null) | User;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pricing-plans".
 */
export interface PricingPlan {
  id: string;
  /**
   * The lesson this pricing plan applies to
   */
  lesson: string | Lesson;
  /**
   * Payment provider for this plan
   */
  provider: 'paypal' | 'stripe' | 'manual';
  /**
   * Provider-specific plan ID (required for PayPal and Stripe)
   */
  providerPlanId?: string | null;
  /**
   * Type of billing
   */
  billingType: 'one_time' | 'subscription';
  /**
   * Billing interval (required for subscription billing)
   */
  interval?: ('month' | 'year') | null;
  /**
   * Price amount
   */
  price: number;
  /**
   * Currency code
   */
  currency: 'ILS' | 'USD' | 'EUR';
  /**
   * Whether this pricing plan is currently active
   */
  isActive?: boolean | null;
  /**
   * User who created this document
   */
  createdBy?: (string | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mcp-audit-logs".
 */
export interface McpAuditLog {
  id: string;
  /**
   * Admin user who initiated the tool call
   */
  adminUserId: string | User;
  /**
   * Tenant scope for the tool call
   */
  tenantId: string | Tenant;
  /**
   * MCP tool name that was executed
   */
  toolName: string;
  /**
   * Sanitized arguments passed to the tool
   */
  args?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Number of records returned by the tool
   */
  resultCount?: number | null;
  /**
   * Whether the tool call succeeded
   */
  success: boolean;
  /**
   * When the tool call occurred
   */
  timestamp: string;
  /**
   * Request correlation ID
   */
  requestId: string;
  /**
   * Tool execution duration in milliseconds
   */
  durationMs?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: string;
  /**
   * You will need to rebuild the website when changing this field.
   */
  from: string;
  to?: {
    type?: ('reference' | 'custom') | null;
    reference?: {
      relationTo: 'pages';
      value: string | Page;
    } | null;
    url?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: string;
  form: string | Form;
  submissionData?:
    | {
        field: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This is a collection of automatically created search results. These results are used by the global site search and will be updated automatically as documents in the CMS are created or updated.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search".
 */
export interface Search {
  id: string;
  title?: string | null;
  priority?: number | null;
  doc:
    | {
        relationTo: 'courses';
        value: string | Course;
      }
    | {
        relationTo: 'posts';
        value: string | Post;
      };
  slug?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
  };
  categories?:
    | {
        relationTo?: string | null;
        categoryID?: string | null;
        title?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * API keys control which collections, resources, tools, and prompts MCP clients can access
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-mcp-api-keys".
 */
export interface PayloadMcpApiKey {
  id: string;
  /**
   * The user that the API key is associated with.
   */
  user: string | User;
  /**
   * A useful label for the API key.
   */
  label?: string | null;
  /**
   * The purpose of the API key.
   */
  description?: string | null;
  courses?: {
    /**
     * Allow clients to find courses.
     */
    find?: boolean | null;
    /**
     * Allow clients to create courses.
     */
    create?: boolean | null;
  };
  chapters?: {
    /**
     * Allow clients to find chapters.
     */
    find?: boolean | null;
    /**
     * Allow clients to create chapters.
     */
    create?: boolean | null;
  };
  lessons?: {
    /**
     * Allow clients to find lessons.
     */
    find?: boolean | null;
    /**
     * Allow clients to create lessons.
     */
    create?: boolean | null;
  };
  exercises?: {
    /**
     * Allow clients to find exercises.
     */
    find?: boolean | null;
  };
  media?: {
    /**
     * Allow clients to find media.
     */
    find?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: string;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'pdf_to_exercises' | 'pdf_to_exercises_v2' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'pdf_to_exercises' | 'pdf_to_exercises_v2' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null)
    | ({
        relationTo: 'categories';
        value: string | Category;
      } | null)
    | ({
        relationTo: 'config_secrets';
        value: string | ConfigSecret;
      } | null)
    | ({
        relationTo: 'config_values';
        value: string | ConfigValue;
      } | null)
    | ({
        relationTo: 'config_audit_logs';
        value: string | ConfigAuditLog;
      } | null)
    | ({
        relationTo: 'conversations';
        value: string | Conversation;
      } | null)
    | ({
        relationTo: 'guest-sessions';
        value: string | GuestSession;
      } | null)
    | ({
        relationTo: 'memory_items';
        value: string | MemoryItem;
      } | null)
    | ({
        relationTo: 'tenants';
        value: string | Tenant;
      } | null)
    | ({
        relationTo: 'courses';
        value: string | Course;
      } | null)
    | ({
        relationTo: 'chapters';
        value: string | Chapter;
      } | null)
    | ({
        relationTo: 'lessons';
        value: string | Lesson;
      } | null)
    | ({
        relationTo: 'exercises';
        value: string | Exercise;
      } | null)
    | ({
        relationTo: 'prompts';
        value: string | Prompt;
      } | null)
    | ({
        relationTo: 'exercise-assets';
        value: string | ExerciseAsset;
      } | null)
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'user-progress';
        value: string | UserProgress;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'posts';
        value: string | Post;
      } | null)
    | ({
        relationTo: 'pricing-plans';
        value: string | PricingPlan;
      } | null)
    | ({
        relationTo: 'mcp-audit-logs';
        value: string | McpAuditLog;
      } | null)
    | ({
        relationTo: 'redirects';
        value: string | Redirect;
      } | null)
    | ({
        relationTo: 'forms';
        value: string | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: string | FormSubmission;
      } | null)
    | ({
        relationTo: 'search';
        value: string | Search;
      } | null)
    | ({
        relationTo: 'payload-mcp-api-keys';
        value: string | PayloadMcpApiKey;
      } | null)
    | ({
        relationTo: 'payload-folders';
        value: string | FolderInterface;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'users';
        value: string | User;
      }
    | {
        relationTo: 'payload-mcp-api-keys';
        value: string | PayloadMcpApiKey;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user:
    | {
        relationTo: 'users';
        value: string | User;
      }
    | {
        relationTo: 'payload-mcp-api-keys';
        value: string | PayloadMcpApiKey;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  hero?:
    | T
    | {
        type?: T;
        richText?: T;
        links?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                    appearance?: T;
                  };
              id?: T;
            };
      };
  layout?:
    | T
    | {
        cta?: T | CallToActionBlockSelect<T>;
        content?: T | ContentBlockSelect<T>;
        archive?: T | ArchiveBlockSelect<T>;
        formBlock?: T | FormBlockSelect<T>;
        html?: T | HtmlBlockSelect<T>;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
      };
  publishedAt?: T;
  generateSlug?: T;
  slug?: T;
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock_select".
 */
export interface CallToActionBlockSelect<T extends boolean = true> {
  richText?: T;
  links?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock_select".
 */
export interface ContentBlockSelect<T extends boolean = true> {
  columns?:
    | T
    | {
        size?: T;
        richText?: T;
        enableLink?: T;
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock_select".
 */
export interface ArchiveBlockSelect<T extends boolean = true> {
  introContent?: T;
  populateBy?: T;
  relationTo?: T;
  categories?: T;
  limit?: T;
  selectedDocs?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock_select".
 */
export interface FormBlockSelect<T extends boolean = true> {
  form?: T;
  enableIntro?: T;
  introContent?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HtmlBlock_select".
 */
export interface HtmlBlockSelect<T extends boolean = true> {
  html?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  createdBy?: T;
  parent?: T;
  breadcrumbs?:
    | T
    | {
        doc?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "config_secrets_select".
 */
export interface ConfigSecretsSelect<T extends boolean = true> {
  key?: T;
  tenant?: T;
  title?: T;
  value?: T;
  enabled?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "config_values_select".
 */
export interface ConfigValuesSelect<T extends boolean = true> {
  domain?: T;
  tenant?: T;
  config?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "config_audit_logs_select".
 */
export interface ConfigAuditLogsSelect<T extends boolean = true> {
  key?: T;
  tenant?: T;
  action?: T;
  actor?: T;
  reason?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "conversations_select".
 */
export interface ConversationsSelect<T extends boolean = true> {
  user?: T;
  guestSession?: T;
  contextRef?: T;
  contextKey?: T;
  exercise?: T;
  messages?:
    | T
    | {
        role?: T;
        content?: T;
        timestamp?: T;
        hidden?: T;
        media?:
          | T
          | {
              mediaId?: T;
              id?: T;
            };
        id?: T;
      };
  summary?: T;
  summaryUpdatedAt?: T;
  summaryUntilTimestamp?: T;
  contextPolicyVersion?: T;
  lastMessageAt?: T;
  archivedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "guest-sessions_select".
 */
export interface GuestSessionsSelect<T extends boolean = true> {
  tokenHash?: T;
  tokenVersion?: T;
  createdAt?: T;
  lastActiveAt?: T;
  expiresAt?: T;
  hardExpiresAt?: T;
  ipHash?: T;
  userAgentHash?: T;
  status?: T;
  claimedByUser?: T;
  claimedAt?: T;
  messageCount?: T;
  updatedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "memory_items_select".
 */
export interface MemoryItemsSelect<T extends boolean = true> {
  userId?: T;
  conversationId?: T;
  contextKey?: T;
  contextLevel?: T;
  type?: T;
  text?: T;
  embedding?: T;
  importance?: T;
  status?: T;
  source?:
    | T
    | {
        sourceConversationId?: T;
        sourceMessageTimestamp?: T;
        sourceMessageRole?: T;
      };
  user?: T;
  conversation?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants_select".
 */
export interface TenantsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses_select".
 */
export interface CoursesSelect<T extends boolean = true> {
  tenant?: T;
  courseLabel?: T;
  title?: T;
  description?: T;
  mediaFiles?: T;
  order?: T;
  status?: T;
  isActive?: T;
  categories?: T;
  prompt?: T;
  courseContextText?: T;
  slug?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
      };
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "chapters_select".
 */
export interface ChaptersSelect<T extends boolean = true> {
  tenant?: T;
  course?: T;
  chapterLabel?: T;
  title?: T;
  adminTitle?: T;
  description?: T;
  mediaFiles?: T;
  order?: T;
  status?: T;
  isActive?: T;
  slug?: T;
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lessons_select".
 */
export interface LessonsSelect<T extends boolean = true> {
  tenant?: T;
  chapter?: T;
  type?: T;
  title?: T;
  description?: T;
  order?: T;
  status?: T;
  isActive?: T;
  introEnabled?: T;
  introDescription?: T;
  introMedia?: T;
  contentFiles?: T;
  lessonContextText?: T;
  prompt?: T;
  slug?: T;
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "exercises_select".
 */
export interface ExercisesSelect<T extends boolean = true> {
  tenant?: T;
  title?: T;
  order?: T;
  lesson?: T;
  slug?: T;
  content?: T;
  createdBy?: T;
  origin?: T;
  sourceDoc?: T;
  conversionJobId?: T;
  sourcePageStart?: T;
  sourcePageEnd?: T;
  sourceOrderInSegment?: T;
  contentHash?: T;
  idempotencyKey?: T;
  specVersion?: T;
  extractionMeta?: T;
  pipelineVersion?: T;
  sourcePageIndex?: T;
  sourceBboxNormalized?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "prompts_select".
 */
export interface PromptsSelect<T extends boolean = true> {
  title?: T;
  key?: T;
  type?: T;
  template?: T;
  status?: T;
  isDefaultForAgentChat?: T;
  tenant?: T;
  usage?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "exercise-assets_select".
 */
export interface ExerciseAssetsSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  googleSub?: T;
  verifiedEmail?: T;
  registrationMethod?: T;
  registeredAt?: T;
  googleProfile?:
    | T
    | {
        name?: T;
      };
  oauthLoginSecretEnc?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-progress_select".
 */
export interface UserProgressSelect<T extends boolean = true> {
  tenant?: T;
  user?: T;
  gradeLevel?: T;
  progressRecords?:
    | T
    | {
        recordType?: T;
        recordId?: T;
        completionPercentage?: T;
        status?: T;
        score?: T;
        lastAccessedAt?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  tenant?: T;
  type?: T;
  externalUrl?: T;
  alt?: T;
  caption?: T;
  createdBy?: T;
  retentionPolicy?: T;
  expiresAt?: T;
  sizes?: T;
  folder?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  heroImage?: T;
  content?: T;
  relatedPosts?: T;
  categories?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  authors?: T;
  populatedAuthors?:
    | T
    | {
        id?: T;
        name?: T;
      };
  generateSlug?: T;
  slug?: T;
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pricing-plans_select".
 */
export interface PricingPlansSelect<T extends boolean = true> {
  lesson?: T;
  provider?: T;
  providerPlanId?: T;
  billingType?: T;
  interval?: T;
  price?: T;
  currency?: T;
  isActive?: T;
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mcp-audit-logs_select".
 */
export interface McpAuditLogsSelect<T extends boolean = true> {
  adminUserId?: T;
  tenantId?: T;
  toolName?: T;
  args?: T;
  resultCount?: T;
  success?: T;
  timestamp?: T;
  requestId?: T;
  durationMs?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?:
    | T
    | {
        type?: T;
        reference?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  fields?:
    | T
    | {
        checkbox?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              id?: T;
              blockName?: T;
            };
        country?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        email?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        message?:
          | T
          | {
              message?: T;
              id?: T;
              blockName?: T;
            };
        number?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        select?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              placeholder?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              required?: T;
              id?: T;
              blockName?: T;
            };
        state?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        textarea?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
      };
  submitButtonLabel?: T;
  confirmationType?: T;
  confirmationMessage?: T;
  redirect?:
    | T
    | {
        url?: T;
      };
  emails?:
    | T
    | {
        emailTo?: T;
        cc?: T;
        bcc?: T;
        replyTo?: T;
        emailFrom?: T;
        subject?: T;
        message?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  submissionData?:
    | T
    | {
        field?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search_select".
 */
export interface SearchSelect<T extends boolean = true> {
  title?: T;
  priority?: T;
  doc?: T;
  slug?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
      };
  categories?:
    | T
    | {
        relationTo?: T;
        categoryID?: T;
        title?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-mcp-api-keys_select".
 */
export interface PayloadMcpApiKeysSelect<T extends boolean = true> {
  user?: T;
  label?: T;
  description?: T;
  courses?:
    | T
    | {
        find?: T;
        create?: T;
      };
  chapters?:
    | T
    | {
        find?: T;
        create?: T;
      };
  lessons?:
    | T
    | {
        find?: T;
        create?: T;
      };
  exercises?:
    | T
    | {
        find?: T;
      };
  media?:
    | T
    | {
        find?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders_select".
 */
export interface PayloadFoldersSelect<T extends boolean = true> {
  name?: T;
  folder?: T;
  documentsAndFolders?: T;
  folderType?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: string;
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?: {
            relationTo: 'pages';
            value: string | Page;
          } | null;
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: string;
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?: {
            relationTo: 'pages';
            value: string | Page;
          } | null;
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskPdf_to_exercises".
 */
export interface TaskPdfToExercises {
  input?: unknown;
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskPdf_to_exercises_v2".
 */
export interface TaskPdfToExercisesV2 {
  input?: unknown;
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?:
      | ({
          relationTo: 'pages';
          value: string | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: string | Post;
        } | null);
    global?: string | null;
    user?: (string | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BannerBlock".
 */
export interface BannerBlock {
  style: 'info' | 'warning' | 'error' | 'success';
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'banner';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CodeBlock".
 */
export interface CodeBlock {
  language?: ('typescript' | 'javascript' | 'css') | null;
  code: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'code';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock".
 */
export interface MediaBlock {
  media: string | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'mediaBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}